Script started on 2021-04-09 22:59:27+05:30 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="78" LINES="12"]
(base) ]0;sandip@sandip-pc: ~/Desktop/Assignments/NS/Assignment 3[01;32msandip@sandip-pc[00m:[01;34m~/Desktop/Assignments/NS/Assignment 3[00m$ [K(base) ]0;sandip@sandip-pc: ~/Desktop/Assignments/NS/Assignment 3[01;32msandip@sandip-pc[00m:[01;34m~/Desktop/Assignments/NS/Assignment 3[00m$ [K(base) ]0;sandip@sandip-pc: ~/Desktop/Assignments/NS/Assignment 3[01;32msandip@sandip-pc[00m:[01;34m~/Desktop/Assignments/NS/Assignment 3[00m$ python kdc.py -p 1234 -o log.txt  -f pwdfile.txt
[2021-04-09 11:01 PM] - Starting server at 127.0.1.1:1234
[2021-04-09 11:01 PM] - Server is listening on 127.0.1.1:1234
[2021-04-09 11:01 PM] - New connection : 127.0.0.1:52452 connected.
[2021-04-09 11:01 PM] - New message from 127.0.0.1:52452 - 301|127.0.35.50|4273|n3RXl5nCx+gSMsqG|alic
[2021-04-09 11:01 PM] - Client Disconnected: 127.0.0.1:52452
[2021-04-09 11:02 PM] - New connection : 127.0.0.1:52456 connected.
[2021-04-09 11:02 PM] - New message from 127.0.0.1:52456 - 301|127.0.1.1|8543|3pNgf6PZymSlY3Z1|bob
[2021-04-09 11:02 PM] - New message from 127.0.0.1:52456 - 305|KrhZqFjxzIwLrDSokJ/JDiVxTuJQMtCqJ4nuCPcpop4=|bob
[2021-04-09 11:02 PM] - Client Disconnected: 127.0.0.1:52456
^CTraceback (most recent call last):
  File "kdc.py", line 84, in <module>
    start()
  File "kdc.py", line 78, in start
    conn, addr = server.accept()
  File "/home/sandip/anaconda3/lib/python3.8/socket.py", line 292, in accept
    fd, addr = self._accept()
KeyboardInterrupt

(base) ]0;sandip@sandip-pc: ~/Desktop/Assignments/NS/Assignment 3[01;32msandip@sandip-pc[00m:[01;34m~/Desktop/Assignments/NS/Assignment 3[00m$ exit
exit

Script done on 2021-04-09 23:02:22+05:30 [COMMAND_EXIT_CODE="130"]
